development:
  adapter: postgresql
  database: db_development
  username: postgres

test:
  adapter: postgresql
  database: db_test
  username: postgres

production:
  adapter: postgresql
  host: db
  database: db_production
  username: postgres

heroku:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
