test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

digitalocean:
  service: S3
  access_key_id: <%= ENV["DO_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["DO_SECRET_ACCESS_KEY"] %>
  region: <%= ENV["DO_REGION"] %>
  bucket: <%= ENV["DO_BUCKET"] %>
  endpoint: <%= ENV["DO_ENDPOINT"] %>
